export const CLIENT__SET_STATUS = 'CLIENT::SET-STATUS'
export const CLIENT__GET_STATUS = 'CLIENT::GET-STATUS'
export const CLIENT__CHECK_FRIEND = 'CLIENT::CHECK_FRIEND'
export const CLIENT__GET_CHECKED_FRIEND = 'CLIENT::GET_CHECKED_FRIEND'

export const REQUEST__FRIENDS_CHECK = 'REQUEST::FRIENDS_CHECK'
export const REQUEST__FIND_OUT_INQUIRIES_FROM_FRIENDS =
  'REQUEST::FIND_OUT_INQUIRIES_FROM_FRIENDS'

export const DIALOG__CONNECTION = 'DIALOG::CONNECTION'
export const DIALOG__SEND_MESSAGE = 'DIALOG::SEND_MESSAGE'
export const DIALOG__GET_MESSAGE = 'DIALOG::GET_MESSAGE'
export const DIALOG__MESSAGE_READ = 'DIALOG::MESSAGE_READ'
export const DIALOG__TYPING = 'DIALOG::TYPING'
export const DIALOG__TYPING_STOP = 'DIALOG::TYPING_STOP'

export const ROOM__CONNECTION = 'ROOM::CONNECTION'
export const ROOM__DISCONNECTION = 'ROOM::DISCONNECTION'
export const ROOM__USER_JOINED = 'ROOM::USER_JOINED'
export const ROOM__USER_LEAVED = 'ROOM::USER_LEAVED'
export const ROOM_GET_INFO_ROOM = 'ROOM::GET_INFO_ROOM'
export const ROOM_GIVE_INFO_ROOM = 'ROOM::GIVE_INFO_ROOM'
