// Client 

export const CLIENT__SET_STATUS         = 'CLIENT::SET-STATUS'
export const CLIENT__GET_STATUS         = 'CLIENT::GET-STATUS'
export const CLIENT__CHECK_FRIEND       = 'CLIENT::CHECK_FRIEND'
export const CLIENT__GET_CHECKED_FRIEND = 'CLIENT::GET_CHECKED_FRIEND'

// Request
export const REQUEST__FRIENDS_CHECK = 'REQUEST::FRIENDS_CHECK'
export const REQUEST__FIND_OUT_INQUIRIES_FROM_FRIENDS = 'REQUEST::FIND_OUT_INQUIRIES_FROM_FRIENDS'