// Client

export const CLIENT__SET_STATUS = 'CLIENT::SET-STATUS'
export const CLIENT__GET_STATUS = 'CLIENT::GET-STATUS'
export const CLIENT__CHECK_FRIEND = 'CLIENT::CHECK_FRIEND'
export const CLIENT__GET_CHECKED_FRIEND = 'CLIENT::GET_CHECKED_FRIEND'

// Request
export const REQUEST__FRIENDS_CHECK = 'REQUEST::FRIENDS_CHECK'
export const REQUEST__FIND_OUT_INQUIRIES_FROM_FRIENDS =
  'REQUEST::FIND_OUT_INQUIRIES_FROM_FRIENDS'

// Dialog

export const DIALOG__CONNECTION = 'DIALOG::CONNECTION'
export const DIALOG__SEND_MESSAGE = 'DIALOG::SEND_MESSAGE'
export const DIALOG__GET_MESSAGE = 'DIALOG::GET_MESSAGE'
export const DIALOG__MESSAGE_READ = 'DIALOG::MESSAGE_READ'
export const DIALOG__TYPING = 'DIALOG::TYPING'
export const DIALOG__TYPING_STOP = 'DIALOG::TYPING_STOP'
