// CLient 

const CLIENT__SET_STATUS         = 'CLIENT::SET-STATUS'
const CLIENT__GET_STATUS         = 'CLIENT::GET-STATUS'
const CLIENT__CHECK_FRIEND       = 'CLIENT::CHECK_FRIEND'
const CLIENT__GET_CHECKED_FRIEND = 'CLIENT::GET_CHECKED_FRIEND'

// Request 

const REQUEST__FRIENDS_CHECK                   = 'REQUEST::FRIENDS_CHECK'
const REQUEST__FIND_OUT_INQUIRIES_FROM_FRIENDS = 'REQUEST::FIND_OUT_INQUIRIES_FROM_FRIENDS'

module.exports = { 
    CLIENT__SET_STATUS,
    CLIENT__GET_STATUS,
    CLIENT__CHECK_FRIEND,
    CLIENT__GET_CHECKED_FRIEND,

    REQUEST__FRIENDS_CHECK,
    REQUEST__FIND_OUT_INQUIRIES_FROM_FRIENDS,
}