const CLIENT__SET_STATUS = 'CLIENT::SET-STATUS'
const CLIENT__GET_STATUS = 'CLIENT::GET-STATUS'
const CLIENT__CHECK_FRIEND = 'CLIENT::CHECK_FRIEND'
const CLIENT__GET_CHECKED_FRIEND = 'CLIENT::GET_CHECKED_FRIEND'

const REQUEST__FRIENDS_CHECK = 'REQUEST::FRIENDS_CHECK'
const REQUEST__FIND_OUT_INQUIRIES_FROM_FRIENDS =
  'REQUEST::FIND_OUT_INQUIRIES_FROM_FRIENDS'

const DIALOG__CONNECTION = 'DIALOG::CONNECTION'
const DIALOG__SEND_MESSAGE = 'DIALOG::SEND_MESSAGE'
const DIALOG__GET_MESSAGE = 'DIALOG::GET_MESSAGE'
const DIALOG__MESSAGE_READ = 'DIALOG::MESSAGE_READ'
const DIALOG__TYPING = 'DIALOG::TYPING'
const DIALOG__TYPING_STOP = 'DIALOG::TYPING_STOP'

const ROOM__CONNECTION = 'ROOM::CONNECTION'
const ROOM__DISCONNECTION = 'ROOM::DISCONNECTION'
const ROOM__USER_JOINED = 'ROOM::USER_JOINED'
const ROOM__USER_LEAVED = 'ROOM::USER_LEAVED'
const ROOM_GET_INFO_ROOM = 'ROOM::GET_INFO_ROOM'
const ROOM_GIVE_INFO_ROOM = 'ROOM::GIVE_INFO_ROOM'

module.exports = {
  CLIENT__SET_STATUS,
  CLIENT__GET_STATUS,
  CLIENT__CHECK_FRIEND,
  CLIENT__GET_CHECKED_FRIEND,

  REQUEST__FRIENDS_CHECK,
  REQUEST__FIND_OUT_INQUIRIES_FROM_FRIENDS,

  DIALOG__CONNECTION,
  DIALOG__SEND_MESSAGE,
  DIALOG__GET_MESSAGE,
  DIALOG__MESSAGE_READ,
  DIALOG__TYPING,
  DIALOG__TYPING_STOP,

  ROOM__CONNECTION,
  ROOM__DISCONNECTION,
  ROOM__USER_JOINED,
  ROOM__USER_LEAVED,
  ROOM_GET_INFO_ROOM,
  ROOM_GIVE_INFO_ROOM,
}
