// CLient 

const CLIENT__SET_STATUS         = 'CLIENT::SET-STATUS'
const CLIENT__GET_STATUS         = 'CLIENT::GET-STATUS'
const CLIENT__CHECK_FRIEND       = 'CLIENT::CHECK_FRIEND'
const CLIENT__GET_CHECKED_FRIEND = 'CLIENT::GET_CHECKED_FRIEND'

// Request 

const REQUEST__FRIENDS_CHECK                   = 'REQUEST::FRIENDS_CHECK'
const REQUEST__FIND_OUT_INQUIRIES_FROM_FRIENDS = 'REQUEST::FIND_OUT_INQUIRIES_FROM_FRIENDS'

// Dialog

const DIALOG__CONNECTION   = 'DIALOG::CONNECTION'
const DIALOG__SEND_MESSAGE = 'DIALOG::SEND_MESSAGE'
const DIALOG__GET_MESSAGE  = 'DIALOG::GET_MESSAGE'
const DIALOG__MESSAGE_READ = 'DIALOG::MESSAGE_READ'
const DIALOG__TYPING       = 'DIALOG::TYPING'
const DIALOG__TYPING_STOP  = 'DIALOG::TYPING_STOP'

module.exports = { 
    CLIENT__SET_STATUS,
    CLIENT__GET_STATUS,
    CLIENT__CHECK_FRIEND,
    CLIENT__GET_CHECKED_FRIEND,

    REQUEST__FRIENDS_CHECK,
    REQUEST__FIND_OUT_INQUIRIES_FROM_FRIENDS,

    DIALOG__CONNECTION,
    DIALOG__SEND_MESSAGE,
    DIALOG__GET_MESSAGE,
    DIALOG__MESSAGE_READ,
    DIALOG__TYPING,
    DIALOG__TYPING_STOP,
}