import React from 'react'

export const ContextChat = React.createContext({
  visibleSidebar: false,
  setVisibleSidebar: () => {},
  urlParams: {},
  currentDialog: {},
  onSendMessage: (e, checkOnPush) => {},
  textInput: '',
  setTextInput: () => {},
  wrapperMessagesDivRef: {},
  goDown: () => {},
  showBtnScroll: false,
  checkPositionScroll: () => {},
  messages: [],
  setMessages: () => {},
  visiblePicker: false,
  toggleVisiblePicker: () => {},
  onSelectEmoji: emoji => {},
  countUnreadMsg: 0,
  setCountUnreadMsg: () => {},
  onInputMessage: e => {},
  isShowChatAct: false,
  usernameChatAct: '',
  combinedFiles: [],
  onRemoveAttachedFiles: id => {},
  isEmptyUploader: false,
  imagesUpload: [],
  videosUpload: [],
  audiosUpload: [],
  documentsUpload: [],
  setImagesUpload: () => {},
  setAudiosUpload: () => {},
  setVideosUpload: () => {},
  setDocumentsUpload: () => {},
  renderStickyDate: () => {},
  parserLinks: message => {},
})
