import React from 'react'

export const ContextCreatingRoom = React.createContext({
  valuesInputs: {},
  setInputsForm: () => {},
  listAddedFriends: [],
  setListAddedFriends: () => {},
  changeCheckboxSecurityKey: () => {},
  changeCheckboxReadyLinks: () => {},
  checkboxSecurityKey: false,
  checkboxReadyLinks: false,
  getPreviewFromLink: (input = 'linkToVideo') => {},
  createRoomHandler: () => {},
  successEdit: false,
  acceptSecurityKey: () => {},
  pasteToTextSecurityKey: () => {},
  urlLogoRoom: '',
  uploadLogoRoomLocal: () => {},
  inviteFriends: friend => {},
  kickOutFromRoom: friend => {},
  filterAddedFriendInRoomContextmenu: () => {},
  listAllLinksToVideos: [],
  appendToListAllLinksToVideos: () => {},
  deleteFromListAllLinksToVideos: () => {},
  refUploadLogo: null,
})
