import React from 'react'

export const ContextSettings = React.createContext({
  cubes: [],
  changeTheme: ref => {},
  arrayImages: [],
  selectImageBackgroundChat: '',
  setSelectImageBackgroundChat: () => {},
  changeSwitchBtn: (nameSwitch, value = NaN) => {},
  switchBtn: {},
  backgroundChatOpen: false,
  setBackgroundChatOpen: () => {},
  imageDirectoryRef: {},
  onToggleImageDirectory: action => {},
  selectedTheme: '',
  addingToFriend: {},
  setAddingToFriend: () => {},
  speedRangeSliderImage: 0,
  setSpeedRangeSliderImage: () => {},
  passwordInput: '',
  setPasswordInput: () => {},
  changePasswordUser: async () => {},
  onSaveSettings: async () => {},
  overlay: {},
  setOverlay: () => {},
  listDevices: {},
  onChooseMicrophoneAndWebcamera: device => {},
  microphoneAndCamera: {},
  previewWebcamera: null,
  isPreviewWebcamera: false,
  setIsPreviewWebcamera: () => {},
  onChooseVolumeDevices: (device, value) => {},
  loading: false,
  inputTokenApi: '',
  setInputTokenApi: () => {},
  displayBrightness: 100,
  setDisplayBrightness: () => {},
  successfulIdentification: false,
  setSuccessfulIdentification: () => {},
})
